### PR TITLE
Add RPC docs

### PR DESCRIPTION
**Pull request by prayank23**

### CODE REVIEW

**Comment by luke-jr** [comment]
These aren't html files and I'm pretty sure won't work at all?

**Comment by prayank23** [comment]
I used it from https://github.com/bitcoin-core/bitcoincore.org/tree/master/_doc/en

**Comment by luke-jr** [comment]
bitcoincore.org isn't a static website and requires processing. Rather than make bitcoinknots.org the same, I'd rather just generate static pages from the docs...

**Comment by prayank23** [comment]
> I'd rather just generate static pages from the docs

That will work for me. Can start with some sort of docs for RPC and improve later if required.

**Pull request closed without merging**
